-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.AMOUNT) AS SALES
FROM PRODUCT P
INNER JOIN 
(
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE;


