-- 코드를 입력하세요
SELECT DISTINCT CAR.CAR_ID, CAR.CAR_TYPE, (DISCOUNT / 100 * 30 * CAR.DAILY_FEE) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIST
ON CAR.CAR_ID = HIST.CAR_ID
LEFT JOIN 
    (SELECT PLAN.CAR_TYPE AS CAR_TYPE,
    TRUNCATE((100 - REPLACE(PLAN.DISCOUNT_RATE, '%', '')), 0) 
    AS DISCOUNT
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
    WHERE PLAN.DURATION_TYPE = '30일 이상') AS PLAN_FEE
ON CAR.CAR_TYPE = PLAN_FEE.CAR_TYPE 
WHERE CAR.CAR_TYPE IN ('세단', 'SUV')
AND CAR.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
    WHERE (START_DATE BETWEEN DATE('2022-11-01') AND DATE('2022-11-30'))
    OR (END_DATE BETWEEN DATE('2022-11-01') AND DATE('2022-11-30'))
    OR (START_DATE < DATE('2022-11-01') AND END_DATE > DATE('2022-11-30'))
)
HAVING FEE BETWEEN 500000 AND (2000000 - 1)
ORDER BY FEE DESC, CAR.CAR_TYPE, CAR.CAR_ID DESC;