-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS 'YEAR', 
MONTH(SALES_DATE) AS 'MONTH', INFO.GENDER AS GENDER,
COUNT(DISTINCT INFO.USER_ID) AS 'USERS'
FROM ONLINE_SALE AS SALE
LEFT JOIN USER_INFO AS INFO
ON SALE.USER_ID = INFO.USER_ID
WHERE INFO.GENDER IS NOT NULL
GROUP BY  YEAR(SALES_DATE), MONTH(SALES_DATE), INFO.GENDER
ORDER BY 1, 2, 3;