# -- 코드를 입력하세요
WITH USER_CONDITION AS (
        SELECT *
        FROM USER_INFO UI
        WHERE DATE_FORMAT(UI.JOINED, '%Y') = '2021'
),
USER_COUNT AS (
    SELECT COUNT(*) AS TOTAL_COUNT
    FROM USER_CONDITION
)

SELECT 
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / UC.TOTAL_COUNT, 1) AS PUCHASED_RATIO
FROM USER_CONDITION U
INNER JOIN ONLINE_SALE S
ON U.USER_ID = S.USER_ID
CROSS JOIN USER_COUNT AS UC
GROUP BY 1, 2
ORDER BY 1, 2


# 2021에 가입 중 상품 구매 / 2021에 가입한 전체 회원수
# 를 년, 월 별로 출력