-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(AMOUNT * P.PRICE) AS TOTAL_SALES
# , AS '총매출'
FROM FOOD_PRODUCT P
JOIN (
        SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
        FROM FOOD_ORDER
        WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
        GROUP BY PRODUCT_ID
    ) O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;