-- 코드를 입력하세요
SELECT HISTORY_ID,
CASE
WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90
THEN 
DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) *
    (SELECT (100 - REPLACE(DISCOUNT_RATE, '%', '')) / 100
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP
    WHERE CC.CAR_TYPE = CP.CAR_TYPE 
    AND REPLACE(DURATION_TYPE, '일 이상', '') = 90
    )
WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30
THEN 
DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) *
    (SELECT (100 - REPLACE(DISCOUNT_RATE, '%', '')) / 100
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP
    WHERE CC.CAR_TYPE = CP.CAR_TYPE 
    AND REPLACE(DURATION_TYPE, '일 이상', '') = 30
    )
WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7
THEN 
DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) *
    (SELECT (100 - REPLACE(DISCOUNT_RATE, '%', '')) / 100
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP
    WHERE CC.CAR_TYPE = CP.CAR_TYPE 
    AND REPLACE(DURATION_TYPE, '일 이상', '') = 7
    )    
ELSE DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1)
END AS FEE
# DAILY_FEE AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CC
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
ON CC.CAR_ID = CH.CAR_ID
WHERE CC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
;