-- 코드를 입력하세요
WITH RECURSIVE RC AS
(
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1
    FROM RC 
    WHERE HOUR < 23
)

SELECT RC.HOUR AS HOUR, COUNT(HOUR(DATETIME)) AS 'COUNT'
FROM RC
LEFT JOIN ANIMAL_OUTS
ON RC.HOUR = HOUR(DATETIME)
GROUP BY RC.HOUR
ORDER BY 1;