-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
((
    SELECT MAX(ED.SIZE_OF_COLONY)
    FROM ECOLI_DATA AS ED
    WHERE DATE_FORMAT(ED.DIFFERENTIATION_DATE, '%Y') 
    = DATE_FORMAT(ECOLI_DATA.DIFFERENTIATION_DATE, '%Y')
    GROUP BY DATE_FORMAT(ED.DIFFERENTIATION_DATE, '%Y')
) - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA 
ORDER BY YEAR, YEAR_DEV;