-- 코드를 작성해주세요
SELECT INFO.ID AS 'ID', NAME.FISH_NAME AS FISH_NAME, INFO.LENGTH AS 'LENGTH'
FROM FISH_INFO AS INFO
LEFT JOIN FISH_NAME_INFO AS NAME
ON INFO.FISH_TYPE = NAME.FISH_TYPE
WHERE INFO.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE INFO.FISH_TYPE = FISH_INFO.FISH_TYPE
);

